### ISSUE TITLE
MODELO DE NEGOCIOS 

### ISSUE THREAD

**Issue by NoeliaGlez** [SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-equipo-de-melissa#3]
[MODELO DE NEGOCIOS CANVAS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-equipo-de-melissa/files/9621754/MODELO.DE.NEGOCIOS.CANVAS.pdf)

**Comment by Valentiin01** [comment]
calificación 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
